### ISSUE TITLE
Add Retina support for Social icons

### ISSUE THREAD

**Issue by brianschildt** [privacore/sharebuttons-wp#11]
https://monosnap.com/file/odZRkCaEbZ1AYJj2oZs4nJR2Fx3uJy

**Comment by miro-orpheus** [comment]
I need more info about this task. Are you need social icons to be changed with another or other thing.

**Comment by brianschildt** [comment]
When looking at the social icons on a Retina display (Macbook pro) the icons does not have the resolution  I'll find some icons to use, the you can change them @miro-orpheus. Will reassign when I have the icons in the correct size

**Comment by miro-orpheus** [comment]
@brianschildt WP Retina 2x works fine. I only need to send me social icons  with size 2x. I tested plugin locally and result is expected.

**Comment by miro-orpheus** [comment]
I found problem with this plugin. In basic version of plugin not allow to regenerate  full size images (previously uploaded). I try to find solution but without success.

**Comment by miro-orpheus** [comment]
I try to fix problem with old full-size images without success.  I see  pro version of plugin support  replace of full-size with new image with big size. If you need to test  I will install plugin on dev. If you found another solution please tell me.

**Comment by brianschildt** [comment]
Let us leave the old images behind. Eventually I can re-upload them, it is not many, after all

**Comment by brianschildt** [comment]
@miro-orpheus - I am just looking at it, is there any other advantages with pro?

**Comment by brianschildt** [comment]
Let's go for this - https://wordpress.org/plugins/wp-retina-2x/

**Comment by miro-orpheus** [comment]
I see this about pro advantages(see screenshot).

![retina-pro](https://cloud.githubusercontent.com/assets/17247291/14454414/21201e38-00a3-11e6-8fae-58f51d5736e9.png)

**Comment by brianschildt** [comment]
OK, sounds like it will save time, I'll get a license key for the Pro version.

**Comment by brianschildt** [comment]
@miro-orpheus I have activate the plugin on dev.

**Comment by miro-orpheus** [comment]
@brianschildt I'm created new  pull request for sharebuttons-wp and wordpress-theme. Please merge them.

**Comment by brianschildt** [comment]
Merged

**Comment by miro-orpheus** [comment]
Please merge again sharebuttons-wp, because I'm added  fix for twitter icon.

**Comment by miro-orpheus** [comment]
Now You can check retina social icons and logos.

**Comment by brianschildt** [comment]
Something is wrong on mobile with Retina display
- Social Icons are to big

Split issue, to focus this on SSP buttons

**Comment by miro-orpheus** [comment]
Issues are fixed
