### ISSUE TITLE
Plugin does not work on version 4.7.3 Wordpress

### ISSUE THREAD

**Issue by hrysakis** [privacore/sharebuttons-wp#27]
Hi,

I have tested the plugin and it does not seem to work. The problem is that I cannot configure the settings of the plugin as long as you see in the attachment:
![settings](https://cloud.githubusercontent.com/assets/6650571/25009680/2a729ee6-2070-11e7-9f35-58f5dbd34314.JPG)

Thanks in advance,
Ioannis Chrysakis

**Comment by brianschildt** [comment]
@hrysakis - thank you for the feedback, looking into it.

**Comment by brianschildt** [comment]
I've looked at it, and to be honest I'm not sure what you need to configure ;-)  The Settings just shows the shortcode for the buttons, if you need to add them manually. Apart from that you can in each post/page see a section where you can activate or deceive the buttons:

![2017-04-21_18-55-33](https://cloud.githubusercontent.com/assets/13692623/25288085/34f475d8-26c4-11e7-9ce6-3352c30b5e63.png)

A bit more info is found in the wiki https://github.com/privacore/sharebuttons-wp/wiki/Share-Buttons-without-tracking-for-WordPress---free-and-Open-Source

**Comment by hrysakis** [comment]
Hi,
@brianschildt thanks for your info. 

I have some remaining issues to raise:
1. Can I apply the plugin functionality to posts rather than pages? In fact we need to display the buttons in a specific category of posts. I have tested it in some posts but the icons does not appear.
2. Nevertheless I have tested it to two different pages with the exact same setting.  In some pages it works fine but in others no any icon appeared. For example page1: https://www.caprice-community.net/faq/ and page2: https://www.caprice-community.net/our-mission/ 
I thought that this has to do with applying shortcodes on the second page, or a potential conflict with the pagebuilder plugin but when I removed any shortcode the problem remained.
To sum-up the crucial point at this moment for us is to support the feature of (1).

Best,
Ioannis Chrysakis

**Comment by brianschildt** [comment]
@hrysakis Thx for the questions.

1. Yes it is possible to use used the buttons on both pages and posts.  
Page example https://www.privacore.com/findx/
Post example: https://www.privacore.com/2017/03/30/basic-features-of-findx-a-private-search-engine/ 

The Shortcode is just for use in corner-cases - otherwise the SSB section should be available on both pages and posts.  

You'll need to add additional code if you will automatically limit it to one category, but you can control it pr. post.

2. From the links you send me, I cannot tell why the problem is occurring, sorry.

**Comment by hrysakis** [comment]
@brianschildt  
The problem is that I cannot find why the plugin does not work properly in posts and in some pages. So at this moment we cannot use it.
Regards.

**Comment by brianschildt** [comment]
I'll ping you in private, let's try to sort it out

**Comment by hrysakis** [comment]
Many thanks for your support!
